### ISSUE TITLE
changes still not visible

### ISSUE THREAD

**Issue by gaubapravar** [flyingchewbacca/icingaweb2-theme-dark#2]
dark screen is still not coming. I copied the required Dark.less file in the  /usr/share/icingaweb2/public/css/themes folder. Even disabled Auto-refresh, and enabled back again. Changes are still not visible. 
When googled about it, it said that you need to edit the path of the background location attribute in Dark.less file where the icingaweb2-dark.png file is present. Even did that, still didnt get anywhere yet.

Please help out. @GumbalMumbal

**Comment by sysmike** [comment]
Mhh thats strange.
Has Dark.less the right permissions (0644 in my case)? 
Is it enabled in your users settings?
