### ISSUE TITLE
Colors in Directory area are a bit light

### ISSUE THREAD

**Issue by asdf1234-deleted** [flyingchewbacca/icingaweb2-theme-dark#3]
Not sure what to modify to resolve, base01 in the CSS? Besides that, the theme rocks!

![image](https://user-images.githubusercontent.com/27829577/47914670-da03f600-de76-11e8-92e1-5e3595f7a4d0.png)

**Comment by sysmike** [comment]
This seems to be an issue with the Icinga Director plugin using its own CSS.
I have not installed said plugin but attempted a fix using the official demo page.
